# http://docs.travis-ci.com/user/build-configuration/

notifications:
    slack: cs373-downing:czYT0ckKXN0tR7YsxwdpjjWi

language: python

python:
    - "3.4"

sudo: false

install:
    - pip3 install --upgrade pip
    - pip3 --version
    - pip3 install -r requirements.txt

before_script:
    - uname -a
    - printenv
    - pip3 list

script:
    - date
    - ls -al
    - make models.html
    - ls -al
    - make IDB1.log
    - ls -al
    - make test
    - ls -al
    - make check