# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

notifications:
  slack: cs373-downing:czYT0ckKXN0tR7YsxwdpjjWi

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install requests
    - pip install -r ./app/requirements.txt

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make model.html
    - ls -al
    - make IDB1.log
    - ls -al
    - make test
    - ls -al
    - make check